"""Helpers for durable technical-documentation tracking."""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ._version import __version__
from .addons_path_manager import AddonsPathManager
from .api_models import (
    DocumentationDocumentSnapshot,
    DocumentationSourceSnapshot,
    DocumentationTrackedFile,
    TechnicalDocumentation,
    TechnicalDocumentationMetadata,
    TechnicalDocumentationStatus,
)
from .source_locator import list_addon_technical_inventory

TECHNICAL_DOC_FILENAME = "architecture.md"
TECHNICAL_DOC_METADATA_FILENAME = "architecture.oduit.json"
TECHNICAL_DOC_SCHEMA_VERSION = "oduit.technical_documentation.v1"
_GENERATED_HEADER_MARKER = "Generated by oduit."
_MANIFEST_FILENAMES = {"__manifest__.py", "__openerp__.py"}
_TRACKED_EXTENSIONS = {
    ".py",
    ".xml",
    ".csv",
    ".js",
    ".ts",
    ".scss",
    ".css",
    ".po",
    ".pot",
    ".md",
    ".rst",
}
_EXCLUDED_DIRS = {
    "__pycache__",
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "htmlcov",
    "node_modules",
    "dist",
    "build",
}
_EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".swp", ".tmp"}
_EXCLUDED_FILENAMES = {".DS_Store", "Thumbs.db", ".coverage"}


def technical_doc_paths(addon_root: str | Path) -> tuple[Path, Path]:
    """Return the technical-documentation Markdown and sidecar paths."""

    docs_dir = Path(addon_root) / "docs"
    return (
        docs_dir / TECHNICAL_DOC_FILENAME,
        docs_dir / TECHNICAL_DOC_METADATA_FILENAME,
    )


def utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string with a Z suffix."""

    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def compute_document_snapshot(doc_path: str | Path) -> DocumentationDocumentSnapshot:
    """Hash the current Markdown document."""

    path = Path(doc_path)
    content = path.read_bytes()
    return DocumentationDocumentSnapshot(
        fingerprint=f"sha256:{hashlib.sha256(content).hexdigest()}",
        size_bytes=len(content),
        line_count=len(path.read_text(encoding="utf-8").splitlines()),
    )


def compute_source_snapshot(
    addon_root: str | Path,
    *,
    module: str,
) -> DocumentationSourceSnapshot:
    """Hash tracked source files under one addon root."""

    root = Path(addon_root)
    inventory = list_addon_technical_inventory(root.as_posix(), module)
    tracked_files: list[DocumentationTrackedFile] = []
    for file_entry in inventory.files:
        absolute_path = Path(file_entry.path)
        relative_path = absolute_path.relative_to(root).as_posix()
        if not _should_track_file(relative_path):
            continue
        file_bytes = absolute_path.read_bytes()
        tracked_files.append(
            DocumentationTrackedFile(
                path=relative_path,
                category=file_entry.category,
                size_bytes=len(file_bytes),
                sha256=hashlib.sha256(file_bytes).hexdigest(),
            )
        )

    tracked_files.sort(key=lambda item: item.path)
    payload = [
        {
            "path": file_entry.path,
            "category": file_entry.category,
            "size_bytes": file_entry.size_bytes,
            "sha256": file_entry.sha256,
        }
        for file_entry in tracked_files
    ]
    fingerprint = hashlib.sha256(_canonical_json_bytes(payload)).hexdigest()
    return DocumentationSourceSnapshot(
        fingerprint=f"sha256:{fingerprint}",
        file_count=len(tracked_files),
        files=tracked_files,
    )


def load_technical_documentation_metadata(
    metadata_path: str | Path,
) -> tuple[TechnicalDocumentationMetadata | None, list[str]]:
    """Load sidecar metadata and return warnings instead of parse exceptions."""

    path = Path(metadata_path)
    if not path.exists():
        return None, []

    try:
        raw_data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return None, [f"Failed to parse documentation metadata: {exc}"]

    if not isinstance(raw_data, dict):
        return None, ["Documentation metadata must be a JSON object."]
    if raw_data.get("schema_version") != TECHNICAL_DOC_SCHEMA_VERSION:
        return (
            None,
            [
                "Documentation metadata has an unsupported schema version: "
                f"{raw_data.get('schema_version')!r}"
            ],
        )

    metadata = _metadata_from_dict(raw_data)
    if metadata is None:
        return None, ["Documentation metadata is missing required fields."]
    return metadata, []


def build_technical_documentation_metadata(
    *,
    bundle: TechnicalDocumentation,
    doc_path: Path,
    metadata_path: Path,
    generation_options: dict[str, Any],
    previous_metadata: TechnicalDocumentationMetadata | None = None,
) -> TechnicalDocumentationMetadata:
    """Build durable metadata after the Markdown file has been written."""

    generated_at = bundle.generated_at or utc_now_iso()
    source_snapshot = compute_source_snapshot(bundle.addon_root, module=bundle.module)
    document_snapshot = compute_document_snapshot(doc_path)
    return TechnicalDocumentationMetadata(
        schema_version=TECHNICAL_DOC_SCHEMA_VERSION,
        module=bundle.module,
        addon_root=_portable_path(Path(bundle.addon_root)),
        doc_path=_metadata_relative_path(doc_path, addon_root=Path(bundle.addon_root)),
        metadata_path=_metadata_relative_path(
            metadata_path,
            addon_root=Path(bundle.addon_root),
        ),
        template=_normalize_template_name(bundle.template),
        created_at=(
            previous_metadata.created_at
            if previous_metadata is not None and previous_metadata.created_at
            else generated_at
        ),
        last_generated_at=generated_at,
        generation_count=(
            previous_metadata.generation_count + 1
            if previous_metadata is not None
            else 1
        ),
        generator={"name": "oduit", "version": __version__},
        generation_options=dict(generation_options),
        evidence_counts=_evidence_counts(bundle),
        source_snapshot=source_snapshot,
        document_snapshot=document_snapshot,
        warnings=[],
    )


def write_technical_documentation_metadata(
    metadata: TechnicalDocumentationMetadata,
    metadata_path: str | Path,
) -> None:
    """Write stable, pretty JSON with a trailing newline."""

    path = Path(metadata_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(metadata.to_dict(), indent=2, sort_keys=True, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )


def inspect_technical_documentation_status(
    *,
    addon_root: str | Path,
    module: str,
) -> TechnicalDocumentationStatus:
    """Return tracking status for one addon."""

    root = Path(addon_root)
    doc_path, metadata_path = technical_doc_paths(root)
    display_root = _portable_path(root)
    display_doc = _portable_path(doc_path)
    display_metadata = _portable_path(metadata_path)
    has_document = doc_path.exists()
    has_metadata = metadata_path.exists()
    generated_by_oduit = has_document and _document_has_generated_header(doc_path)

    if not has_document and not has_metadata:
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="missing",
        )

    if has_document and not has_metadata:
        remediation = []
        if generated_by_oduit:
            remediation.append(
                "Regenerate the technical documentation with oduit to create "
                "tracking metadata."
            )
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="untracked",
            has_document=True,
            generated_by_oduit=generated_by_oduit,
            remediation=remediation,
        )

    metadata, warnings = load_technical_documentation_metadata(metadata_path)
    if metadata is None:
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="metadata_invalid",
            has_document=has_document,
            has_metadata=True,
            generated_by_oduit=generated_by_oduit,
            warnings=warnings,
            remediation=[
                "Fix or remove the invalid sidecar, then regenerate the "
                "technical documentation with oduit."
            ],
        )

    warnings = list(warnings)
    if metadata.addon_root and metadata.addon_root != display_root:
        warnings.append("Metadata addon_root differs from current addon root.")

    status = TechnicalDocumentationStatus(
        module=module,
        addon_root=display_root,
        doc_path=display_doc,
        metadata_path=display_metadata,
        status="missing_document",
        has_document=has_document,
        has_metadata=True,
        generated_by_oduit=generated_by_oduit or True,
        created_at=metadata.created_at,
        last_generated_at=metadata.last_generated_at,
        warnings=warnings,
    )

    if not has_document:
        status.remediation.append(
            "Restore or regenerate the missing Markdown document."
        )
        return status

    current_document = compute_document_snapshot(doc_path)
    current_source = compute_source_snapshot(root, module=module)
    stored_document = metadata.document_snapshot
    stored_source = metadata.source_snapshot
    if stored_document is None or stored_source is None:
        status.status = "metadata_invalid"
        status.warnings.append(
            "Documentation metadata is missing source or document snapshots."
        )
        status.remediation.append(
            "Regenerate the technical documentation with oduit to rebuild "
            "tracking metadata."
        )
        return status

    status.generated_by_oduit = True
    status.document_edited_since_last_generation = (
        current_document.fingerprint != stored_document.fingerprint
    )
    status.source_changed_since_last_generation = (
        current_source.fingerprint != stored_source.fingerprint
    )
    (
        status.changed_files,
        status.added_files,
        status.removed_files,
    ) = _diff_source_files(stored_source, current_source)

    if (
        not status.document_edited_since_last_generation
        and not status.source_changed_since_last_generation
    ):
        status.status = "up_to_date"
        status.up_to_date = True
        return status

    if status.document_edited_since_last_generation and (
        not status.source_changed_since_last_generation
    ):
        status.status = "document_edited"
        status.remediation.append(
            "Compare the Markdown edits before overwriting with a fresh " "generation."
        )
        return status

    if status.source_changed_since_last_generation and (
        not status.document_edited_since_last_generation
    ):
        status.status = "source_changed"
        status.remediation.append(
            "Regenerate or manually review the architecture document."
        )
        return status

    status.status = "source_and_document_changed"
    status.remediation.append(
        "Review both the source changes and manual document edits before "
        "overwriting the tracked document."
    )
    return status


def inspect_all_technical_documentation_statuses(
    *,
    addons_path: str,
    select_dir: str | None = None,
) -> list[TechnicalDocumentationStatus]:
    """Scan configured addons and return status for each addon."""

    statuses: list[TechnicalDocumentationStatus] = []
    for module, addon_root in _iter_addon_roots(addons_path, select_dir=select_dir):
        statuses.append(
            inspect_technical_documentation_status(
                addon_root=addon_root,
                module=module,
            )
        )
    return sorted(statuses, key=lambda item: (item.module, item.addon_root))


def _canonical_json_bytes(data: Any) -> bytes:
    return json.dumps(
        data,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def _should_track_file(relative_path: str) -> bool:
    path = Path(relative_path)
    normalized = path.as_posix()
    if normalized in {
        f"docs/{TECHNICAL_DOC_FILENAME}",
        f"docs/{TECHNICAL_DOC_METADATA_FILENAME}",
    }:
        return False
    if path.name in _EXCLUDED_FILENAMES:
        return False
    if path.suffix.lower() in _EXCLUDED_SUFFIXES:
        return False
    if any(part in _EXCLUDED_DIRS for part in path.parts):
        return False
    if normalized.startswith("docs/_build/"):
        return False
    if normalized.startswith("docs/") and path.suffix.lower() in {".html", ".pdf"}:
        return False
    if path.name in _MANIFEST_FILENAMES:
        return True
    return path.suffix.lower() in _TRACKED_EXTENSIONS


def _metadata_from_dict(data: dict[str, Any]) -> TechnicalDocumentationMetadata | None:
    required_text_fields = ("module", "addon_root", "doc_path", "metadata_path")
    if any(
        not isinstance(data.get(field_name), str) for field_name in required_text_fields
    ):
        return None

    source_snapshot = _source_snapshot_from_dict(data.get("source_snapshot"))
    document_snapshot = _document_snapshot_from_dict(data.get("document_snapshot"))
    if source_snapshot is None or document_snapshot is None:
        return None

    return TechnicalDocumentationMetadata(
        schema_version=str(data.get("schema_version", TECHNICAL_DOC_SCHEMA_VERSION)),
        module=str(data["module"]),
        addon_root=str(data["addon_root"]),
        doc_path=str(data["doc_path"]),
        metadata_path=str(data["metadata_path"]),
        template=str(data.get("template", "arc42-addon-v1")),
        created_at=_optional_str(data.get("created_at")),
        last_generated_at=_optional_str(data.get("last_generated_at")),
        generation_count=int(data.get("generation_count", 0) or 0),
        generator=(
            dict(data.get("generator", {}))
            if isinstance(data.get("generator"), dict)
            else {}
        ),
        generation_options=(
            dict(data.get("generation_options", {}))
            if isinstance(data.get("generation_options"), dict)
            else {}
        ),
        evidence_counts=(
            {
                str(key): int(value)
                for key, value in data.get("evidence_counts", {}).items()
            }
            if isinstance(data.get("evidence_counts"), dict)
            else {}
        ),
        source_snapshot=source_snapshot,
        document_snapshot=document_snapshot,
        warnings=list(data.get("warnings", []))
        if isinstance(data.get("warnings"), list)
        else [],
    )


def _source_snapshot_from_dict(data: Any) -> DocumentationSourceSnapshot | None:
    if not isinstance(data, dict):
        return None
    files_data = data.get("files")
    if not isinstance(files_data, list):
        return None
    files: list[DocumentationTrackedFile] = []
    for item in files_data:
        if not isinstance(item, dict):
            return None
        path = item.get("path")
        category = item.get("category")
        if not isinstance(path, str) or not isinstance(category, str):
            return None
        files.append(
            DocumentationTrackedFile(
                path=path,
                category=category,
                size_bytes=_optional_int(item.get("size_bytes")),
                sha256=_optional_str(item.get("sha256")),
            )
        )
    return DocumentationSourceSnapshot(
        algorithm=str(data.get("algorithm", "sha256")),
        fingerprint=str(data.get("fingerprint", "")),
        file_count=int(data.get("file_count", len(files)) or 0),
        files=files,
    )


def _document_snapshot_from_dict(data: Any) -> DocumentationDocumentSnapshot | None:
    if not isinstance(data, dict):
        return None
    fingerprint = data.get("fingerprint")
    if not isinstance(fingerprint, str):
        return None
    return DocumentationDocumentSnapshot(
        algorithm=str(data.get("algorithm", "sha256")),
        fingerprint=fingerprint,
        size_bytes=_optional_int(data.get("size_bytes")),
        line_count=_optional_int(data.get("line_count")),
    )


def _optional_int(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _optional_str(value: Any) -> str | None:
    return value if isinstance(value, str) else None


def _portable_path(path: Path) -> str:
    resolved = path.resolve(strict=False)
    try:
        return resolved.relative_to(Path.cwd()).as_posix()
    except ValueError:
        return resolved.as_posix()


def _metadata_relative_path(path: Path, *, addon_root: Path) -> str:
    resolved_path = path.resolve(strict=False)
    resolved_root = addon_root.resolve(strict=False)
    try:
        return resolved_path.relative_to(resolved_root).as_posix()
    except ValueError:
        return _portable_path(resolved_path)


def _normalize_template_name(template: str) -> str:
    return "arc42-addon-v1" if template == "arc42" else template


def _evidence_counts(bundle: TechnicalDocumentation) -> dict[str, int]:
    inventory = bundle.technical_inventory
    addon_doc = bundle.addon_documentation
    recommended_tests = 0
    models = 0
    if addon_doc is not None:
        if addon_doc.model_inventory is not None:
            models = len(addon_doc.model_inventory.models)
        tests = addon_doc.recommended_tests.get("tests")
        if isinstance(tests, list):
            recommended_tests = len(tests)
    return {
        "models": models,
        "xml_records": len(getattr(inventory, "xml_records", []) or []),
        "routes": len(getattr(inventory, "http_routes", []) or []),
        "security_files": len(getattr(inventory, "security_files", []) or []),
        "migration_files": len(getattr(inventory, "migration_files", []) or []),
        "recommended_tests": recommended_tests,
        "todo_markers": len(getattr(inventory, "todo_markers", []) or []),
        "warnings": len(bundle.warnings),
        "remediation": len(bundle.remediation),
    }


def _document_has_generated_header(doc_path: Path) -> bool:
    try:
        return _GENERATED_HEADER_MARKER in doc_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def _diff_source_files(
    old_snapshot: DocumentationSourceSnapshot,
    new_snapshot: DocumentationSourceSnapshot,
) -> tuple[list[str], list[str], list[str]]:
    old_by_path = {file_entry.path: file_entry for file_entry in old_snapshot.files}
    new_by_path = {file_entry.path: file_entry for file_entry in new_snapshot.files}
    added_files = sorted(set(new_by_path) - set(old_by_path))
    removed_files = sorted(set(old_by_path) - set(new_by_path))
    changed_files = sorted(
        path
        for path in set(old_by_path) & set(new_by_path)
        if old_by_path[path].sha256 != new_by_path[path].sha256
    )
    return changed_files, added_files, removed_files


def _iter_addon_roots(
    addons_path: str,
    *,
    select_dir: str | None,
) -> list[tuple[str, str]]:
    addon_roots: list[tuple[str, str]] = []
    seen_roots: set[str] = set()
    for configured_path in AddonsPathManager(addons_path).get_configured_paths():
        base_path = Path(configured_path)
        if select_dir is not None and base_path.name != select_dir:
            continue
        if not base_path.is_dir():
            continue
        for child in sorted(base_path.iterdir()):
            if not child.is_dir():
                continue
            if not any((child / filename).exists() for filename in _MANIFEST_FILENAMES):
                continue
            child_str = child.resolve(strict=False).as_posix()
            if child_str in seen_roots:
                continue
            seen_roots.add(child_str)
            addon_roots.append((child.name, child_str))
    return addon_roots
