"""Helpers for durable technical-documentation tracking."""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from difflib import unified_diff
from pathlib import Path
from typing import Any

from ._version import __version__
from .addons_path_manager import AddonsPathManager
from .api_models import (
    DocumentationDocumentSnapshot,
    DocumentationSourceSnapshot,
    DocumentationTrackedFile,
    TechnicalDocumentation,
    TechnicalDocumentationGeneratedBlock,
    TechnicalDocumentationMetadata,
    TechnicalDocumentationStatus,
    TechnicalEvidenceDiffEntry,
    TechnicalEvidenceDiffResult,
    TechnicalEvidenceMetadata,
)
from .documentation_policy import DocumentationDirectoryPolicy
from .managed_markdown import (
    parse_evidence_snapshot_blocks,
    parse_generated_blocks,
    sha256_text,
)
from .source_locator import list_addon_technical_inventory

TECHNICAL_DOC_FILENAME = "architecture.md"
TECHNICAL_DOC_METADATA_FILENAME = "architecture.oduit.json"
TECHNICAL_DOC_SCHEMA_VERSION = "oduit.technical_documentation.v1"
TECHNICAL_REPORT_FILENAME = TECHNICAL_DOC_FILENAME
TECHNICAL_REPORT_METADATA_FILENAME = TECHNICAL_DOC_METADATA_FILENAME
TECHNICAL_EVIDENCE_FILENAME = "architecture.evidence.md"
TECHNICAL_EVIDENCE_METADATA_FILENAME = "architecture.evidence.oduit.json"
TECHNICAL_EVIDENCE_SCHEMA_VERSION = "oduit.technical_evidence.v1"
TECHNICAL_DOC_STATUS_RANK = {
    "metadata_invalid": 10,
    "missing_document": 20,
    "missing": 30,
    "untracked": 40,
    "generated_blocks_edited": 50,
    "generated_blocks_stale": 60,
    "source_and_document_changed": 70,
    "source_changed": 80,
    "document_edited": 90,
    "up_to_date": 999,
}
_GENERATED_HEADER_MARKER = "Generated by oduit."
_MANIFEST_FILENAMES = {"__manifest__.py", "__openerp__.py"}
_TRACKED_EXTENSIONS = {
    ".py",
    ".xml",
    ".csv",
    ".js",
    ".ts",
    ".scss",
    ".css",
    ".po",
    ".pot",
    ".md",
    ".rst",
}
_EXCLUDED_DIRS = {
    "__pycache__",
    ".git",
    ".hg",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "htmlcov",
    "node_modules",
    "dist",
    "build",
}
_EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".swp", ".tmp"}
_EXCLUDED_FILENAMES = {".DS_Store", "Thumbs.db", ".coverage"}


def technical_doc_paths(addon_root: str | Path) -> tuple[Path, Path]:
    """Return the technical-documentation Markdown and sidecar paths."""

    docs_dir = Path(addon_root) / "docs"
    return (
        docs_dir / TECHNICAL_DOC_FILENAME,
        docs_dir / TECHNICAL_DOC_METADATA_FILENAME,
    )


def technical_evidence_paths(addon_root: str | Path) -> tuple[Path, Path]:
    """Return technical-evidence Markdown and sidecar paths."""

    docs_dir = Path(addon_root) / "docs"
    return (
        docs_dir / TECHNICAL_EVIDENCE_FILENAME,
        docs_dir / TECHNICAL_EVIDENCE_METADATA_FILENAME,
    )


def utc_now_iso() -> str:
    """Return the current UTC time as an ISO-8601 string with a Z suffix."""

    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def compute_document_snapshot(doc_path: str | Path) -> DocumentationDocumentSnapshot:
    """Hash the current Markdown document."""

    path = Path(doc_path)
    content = path.read_bytes()
    return DocumentationDocumentSnapshot(
        fingerprint=f"sha256:{hashlib.sha256(content).hexdigest()}",
        size_bytes=len(content),
        line_count=len(path.read_text(encoding="utf-8").splitlines()),
    )


def compute_source_snapshot(
    addon_root: str | Path,
    *,
    module: str,
) -> DocumentationSourceSnapshot:
    """Hash tracked source files under one addon root."""

    root = Path(addon_root)
    inventory = list_addon_technical_inventory(root.as_posix(), module)
    tracked_files: list[DocumentationTrackedFile] = []
    for file_entry in inventory.files:
        absolute_path = Path(file_entry.path)
        relative_path = absolute_path.relative_to(root).as_posix()
        if not _should_track_file(relative_path):
            continue
        file_bytes = absolute_path.read_bytes()
        tracked_files.append(
            DocumentationTrackedFile(
                path=relative_path,
                category=file_entry.category,
                size_bytes=len(file_bytes),
                sha256=hashlib.sha256(file_bytes).hexdigest(),
            )
        )

    tracked_files.sort(key=lambda item: item.path)
    payload = [
        {
            "path": file_entry.path,
            "category": file_entry.category,
            "size_bytes": file_entry.size_bytes,
            "sha256": file_entry.sha256,
        }
        for file_entry in tracked_files
    ]
    fingerprint = hashlib.sha256(_canonical_json_bytes(payload)).hexdigest()
    return DocumentationSourceSnapshot(
        fingerprint=f"sha256:{fingerprint}",
        file_count=len(tracked_files),
        files=tracked_files,
    )


def load_technical_documentation_metadata(
    metadata_path: str | Path,
) -> tuple[TechnicalDocumentationMetadata | None, list[str]]:
    """Load sidecar metadata and return warnings instead of parse exceptions."""

    path = Path(metadata_path)
    if not path.exists():
        return None, []

    try:
        raw_data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return None, [f"Failed to parse documentation metadata: {exc}"]

    if not isinstance(raw_data, dict):
        return None, ["Documentation metadata must be a JSON object."]
    if raw_data.get("schema_version") != TECHNICAL_DOC_SCHEMA_VERSION:
        return (
            None,
            [
                "Documentation metadata has an unsupported schema version: "
                f"{raw_data.get('schema_version')!r}"
            ],
        )

    metadata = _metadata_from_dict(raw_data)
    if metadata is None:
        return None, ["Documentation metadata is missing required fields."]
    return metadata, []


def load_technical_evidence_metadata(
    metadata_path: str | Path,
) -> tuple[TechnicalEvidenceMetadata | None, list[str]]:
    """Load evidence sidecar metadata and return warnings on parse failures."""

    path = Path(metadata_path)
    if not path.exists():
        return None, []
    try:
        raw_data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        return None, [f"Failed to parse evidence metadata: {exc}"]
    if not isinstance(raw_data, dict):
        return None, ["Evidence metadata must be a JSON object."]
    if raw_data.get("schema_version") != TECHNICAL_EVIDENCE_SCHEMA_VERSION:
        return (
            None,
            [
                "Evidence metadata has an unsupported schema version: "
                f"{raw_data.get('schema_version')!r}"
            ],
        )
    metadata = _evidence_metadata_from_dict(raw_data)
    if metadata is None:
        return None, ["Evidence metadata is missing required fields."]
    return metadata, []


def build_technical_documentation_metadata(
    *,
    bundle: TechnicalDocumentation,
    doc_path: Path,
    metadata_path: Path,
    generation_options: dict[str, Any],
    previous_metadata: TechnicalDocumentationMetadata | None = None,
    path_base_dir: Path | None = None,
    source_addon_root: Path | None = None,
    generated_blocks: list[TechnicalDocumentationGeneratedBlock] | None = None,
) -> TechnicalDocumentationMetadata:
    """Build durable metadata after the Markdown file has been written."""

    generated_at = bundle.generated_at or utc_now_iso()
    snapshot_root = (
        source_addon_root or Path(bundle.source_addon_root or bundle.addon_root)
    ).resolve(strict=False)
    storage_base = (
        path_base_dir.resolve(strict=False)
        if path_base_dir is not None
        else Path.cwd().resolve(strict=False)
    )
    source_snapshot = compute_source_snapshot(snapshot_root, module=bundle.module)
    document_snapshot = compute_document_snapshot(doc_path)
    detected_generated_blocks = (
        generated_blocks
        if generated_blocks is not None
        else _generated_blocks_from_document(doc_path)
    )
    return TechnicalDocumentationMetadata(
        schema_version=TECHNICAL_DOC_SCHEMA_VERSION,
        module=bundle.module,
        addon_root=_portable_path(snapshot_root, base_dir=storage_base),
        doc_path=_portable_path(doc_path, base_dir=storage_base),
        metadata_path=_portable_path(metadata_path, base_dir=storage_base),
        template=_normalize_template_name(bundle.template),
        created_at=(
            previous_metadata.created_at
            if previous_metadata is not None and previous_metadata.created_at
            else generated_at
        ),
        last_generated_at=generated_at,
        generation_count=(
            previous_metadata.generation_count + 1
            if previous_metadata is not None
            else 1
        ),
        generator={"name": "oduit", "version": __version__},
        generation_options=dict(generation_options),
        evidence_counts=_evidence_counts(bundle),
        source_snapshot=source_snapshot,
        document_snapshot=document_snapshot,
        generated_blocks=detected_generated_blocks,
        refresh_count=(
            previous_metadata.refresh_count if previous_metadata is not None else 0
        ),
        last_refreshed_at=(
            previous_metadata.last_refreshed_at
            if previous_metadata is not None
            else None
        ),
        reviewed_at=None,
        reviewed_by=None,
        review_note=None,
        warnings=[],
    )


def build_technical_evidence_metadata(
    *,
    bundle: TechnicalDocumentation,
    evidence_path: Path,
    metadata_path: Path,
    generation_options: dict[str, Any],
    previous_metadata: TechnicalEvidenceMetadata | None = None,
    path_base_dir: Path | None = None,
    source_addon_root: Path | None = None,
    generated_blocks: list[TechnicalDocumentationGeneratedBlock] | None = None,
) -> TechnicalEvidenceMetadata:
    """Build durable evidence metadata after writing evidence markdown."""

    generated_at = bundle.generated_at or utc_now_iso()
    snapshot_root = (
        source_addon_root or Path(bundle.source_addon_root or bundle.addon_root)
    ).resolve(strict=False)
    storage_base = (
        path_base_dir.resolve(strict=False)
        if path_base_dir is not None
        else Path.cwd().resolve(strict=False)
    )
    source_snapshot = compute_source_snapshot(snapshot_root, module=bundle.module)
    evidence_document_snapshot = compute_document_snapshot(evidence_path)
    detected_generated_blocks = (
        generated_blocks
        if generated_blocks is not None
        else _generated_blocks_from_document(evidence_path)
    )
    previous_version = previous_metadata.evidence_version if previous_metadata else 0
    return TechnicalEvidenceMetadata(
        schema_version=TECHNICAL_EVIDENCE_SCHEMA_VERSION,
        module=bundle.module,
        addon_root=_portable_path(snapshot_root, base_dir=storage_base),
        evidence_path=_portable_path(evidence_path, base_dir=storage_base),
        metadata_path=_portable_path(metadata_path, base_dir=storage_base),
        template="arc42-evidence-v1",
        evidence_version=max(1, previous_version + 1),
        created_at=(
            previous_metadata.created_at
            if previous_metadata is not None and previous_metadata.created_at
            else generated_at
        ),
        last_generated_at=generated_at,
        generator={"name": "oduit", "version": __version__},
        generation_options=dict(generation_options),
        evidence_counts=_evidence_counts(bundle),
        source_snapshot=source_snapshot,
        evidence_document_snapshot=evidence_document_snapshot,
        generated_blocks=detected_generated_blocks,
        warnings=[],
    )


def accept_reviewed_technical_documentation(
    *,
    addon_root: str | Path,
    module: str,
    metadata_path: str | Path,
    reviewed_by: str,
    review_note: str,
    force: bool = False,
    path_base_dir: Path | None = None,
) -> TechnicalDocumentationMetadata:
    """Accept a manually polished technical document without creating a generation."""

    root = Path(addon_root).resolve(strict=False)
    doc_path, _ = technical_doc_paths(root)
    metadata, warnings = load_technical_documentation_metadata(metadata_path)
    if metadata is None:
        details = "; ".join(warnings) if warnings else "metadata is missing"
        raise ValueError(f"Cannot accept reviewed documentation: {details}")
    if not doc_path.exists():
        raise FileNotFoundError(f"Technical documentation file is missing: {doc_path}")
    if metadata.source_snapshot is None:
        raise ValueError(
            "Cannot accept reviewed documentation: missing source snapshot."
        )
    if metadata.document_snapshot is None:
        raise ValueError(
            "Cannot accept reviewed documentation: missing document snapshot."
        )

    storage_base = (
        path_base_dir.resolve(strict=False)
        if path_base_dir is not None
        else Path.cwd().resolve(strict=False)
    )
    current_source = compute_source_snapshot(root, module=module)
    if not force and current_source.fingerprint != metadata.source_snapshot.fingerprint:
        raise ValueError(
            "Source files changed since the last generation; "
            "regenerate first or retry with --force."
        )

    metadata.document_snapshot = compute_document_snapshot(doc_path)
    metadata.reviewed_at = utc_now_iso()
    metadata.reviewed_by = reviewed_by
    metadata.review_note = review_note
    metadata.addon_root = _portable_path(root, base_dir=storage_base)
    metadata.doc_path = _portable_path(doc_path, base_dir=storage_base)
    metadata.metadata_path = _portable_path(
        Path(metadata_path).resolve(strict=False), base_dir=storage_base
    )
    return metadata


def write_technical_documentation_metadata(
    metadata: TechnicalDocumentationMetadata,
    metadata_path: str | Path,
) -> None:
    """Write stable, pretty JSON with a trailing newline."""

    path = Path(metadata_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(metadata.to_dict(), indent=2, sort_keys=True, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )


def write_technical_evidence_metadata(
    metadata: TechnicalEvidenceMetadata,
    metadata_path: str | Path,
) -> None:
    """Write stable JSON metadata for evidence documents."""

    path = Path(metadata_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(metadata.to_dict(), indent=2, sort_keys=True, ensure_ascii=False)
        + "\n",
        encoding="utf-8",
    )


def inspect_technical_documentation_status(
    *,
    addon_root: str | Path,
    module: str,
    path_base_dir: Path | None = None,
) -> TechnicalDocumentationStatus:
    """Return tracking status for one addon."""

    root = Path(addon_root).resolve(strict=False)
    doc_path, metadata_path = technical_doc_paths(root)
    storage_base = (
        path_base_dir.resolve(strict=False)
        if path_base_dir is not None
        else Path.cwd().resolve(strict=False)
    )
    display_root = _portable_path(root, base_dir=storage_base)
    display_doc = _portable_path(doc_path, base_dir=storage_base)
    display_metadata = _portable_path(metadata_path, base_dir=storage_base)
    has_document = doc_path.exists()
    has_metadata = metadata_path.exists()
    generated_by_oduit = has_document and _document_has_generated_header(doc_path)

    if not has_document and not has_metadata:
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="missing",
        )

    if has_document and not has_metadata:
        remediation = []
        if generated_by_oduit:
            remediation.append(
                "Regenerate the technical documentation with oduit to create "
                "tracking metadata."
            )
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="untracked",
            has_document=True,
            generated_by_oduit=generated_by_oduit,
            remediation=remediation,
        )

    metadata, warnings = load_technical_documentation_metadata(metadata_path)
    if metadata is None:
        return TechnicalDocumentationStatus(
            module=module,
            addon_root=display_root,
            doc_path=display_doc,
            metadata_path=display_metadata,
            status="metadata_invalid",
            has_document=has_document,
            has_metadata=True,
            generated_by_oduit=generated_by_oduit,
            warnings=warnings,
            remediation=[
                "Fix or remove the invalid sidecar, then regenerate the "
                "technical documentation with oduit."
            ],
        )

    warnings = list(warnings)
    stored_addon_root = _resolve_metadata_path(
        metadata.addon_root,
        base_dir=storage_base,
    )
    if stored_addon_root != root:
        warnings.append("Metadata addon_root differs from current addon root.")

    status = TechnicalDocumentationStatus(
        module=module,
        addon_root=display_root,
        doc_path=display_doc,
        metadata_path=display_metadata,
        status="missing_document",
        has_document=has_document,
        has_metadata=True,
        generated_by_oduit=generated_by_oduit or True,
        generated_block_count=len(metadata.generated_blocks),
        created_at=metadata.created_at,
        last_generated_at=metadata.last_generated_at,
        generation_count=metadata.generation_count,
        generation_options=dict(metadata.generation_options or {}),
        evidence_counts=dict(metadata.evidence_counts or {}),
        template=metadata.template,
        warnings=warnings,
    )

    if not has_document:
        status.remediation.append(
            "Restore or regenerate the missing Markdown document."
        )
        return status

    current_document = compute_document_snapshot(doc_path)
    current_source = compute_source_snapshot(root, module=module)
    stored_document = metadata.document_snapshot
    stored_source = metadata.source_snapshot
    if stored_document is None or stored_source is None:
        status.status = "metadata_invalid"
        status.warnings.append(
            "Documentation metadata is missing source or document snapshots."
        )
        status.remediation.append(
            "Regenerate the technical documentation with oduit to rebuild "
            "tracking metadata."
        )
        return status

    status.generated_by_oduit = True
    status.document_edited_since_last_generation = (
        current_document.fingerprint != stored_document.fingerprint
    )
    status.source_changed_since_last_generation = (
        current_source.fingerprint != stored_source.fingerprint
    )

    try:
        parsed_blocks = parse_generated_blocks(doc_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        parsed_blocks = []
        status.warnings.append(f"Failed to parse managed markdown blocks: {exc}")
    parsed_by_id = {block.id: block for block in parsed_blocks}
    expected_by_id = {block.id: block for block in metadata.generated_blocks}
    status.generated_block_count = len(parsed_blocks)
    status.missing_generated_blocks = sorted(
        block_id for block_id in expected_by_id if block_id not in parsed_by_id
    )
    status.unknown_generated_blocks = sorted(
        block_id for block_id in parsed_by_id if block_id not in expected_by_id
    )
    status.edited_generated_blocks = sorted(
        block_id
        for block_id, parsed in parsed_by_id.items()
        if parsed.metadata.get("content_sha256") != sha256_text(parsed.body)
    )
    if status.source_changed_since_last_generation:
        status.stale_generated_blocks = sorted(
            block_id
            for block_id in expected_by_id
            if block_id not in status.edited_generated_blocks
        )
    else:
        status.stale_generated_blocks = []
    status.generated_blocks_up_to_date = (
        not status.stale_generated_blocks
        and not status.edited_generated_blocks
        and not status.missing_generated_blocks
    )
    (
        status.changed_files,
        status.added_files,
        status.removed_files,
    ) = _diff_source_files(stored_source, current_source)

    if (
        not status.document_edited_since_last_generation
        and not status.source_changed_since_last_generation
        and status.generated_blocks_up_to_date
    ):
        status.status = "up_to_date"
        status.up_to_date = True
        return status

    if status.edited_generated_blocks:
        status.status = "generated_blocks_edited"
        status.remediation.append(
            "Resolve manual edits inside managed generated blocks "
            "or force-refresh them."
        )
        return status

    if status.stale_generated_blocks:
        status.status = "generated_blocks_stale"
        status.remediation.append(
            "Run technical documentation refresh to update "
            "stale managed generated blocks."
        )
        return status

    if status.document_edited_since_last_generation and (
        not status.source_changed_since_last_generation
    ):
        status.status = "document_edited"
        status.remediation.append(
            "Compare the Markdown edits before overwriting with a fresh generation."
        )
        return status

    if status.source_changed_since_last_generation and (
        not status.document_edited_since_last_generation
    ):
        status.status = "source_changed"
        status.remediation.append(
            "Regenerate or manually review the architecture document."
        )
        return status

    status.status = "source_and_document_changed"
    status.remediation.append(
        "Review both the source changes and manual document edits before "
        "overwriting the tracked document."
    )
    return status


def inspect_all_technical_documentation_statuses(
    *,
    addons_path: str,
    select_dir: str | None = None,
    path_base_dir: Path | None = None,
    documentation_policy: DocumentationDirectoryPolicy | None = None,
) -> list[TechnicalDocumentationStatus]:
    """Scan configured addons and return status for each addon."""

    statuses: list[TechnicalDocumentationStatus] = []
    policy = documentation_policy or DocumentationDirectoryPolicy(
        configured=False,
        allowed_dirs=(),
    )
    for module, addon_root in _iter_addon_roots(
        addons_path,
        select_dir=select_dir,
        path_base_dir=path_base_dir,
    ):
        if not policy.is_allowed(addon_root):
            continue
        statuses.append(
            inspect_technical_documentation_status(
                addon_root=addon_root,
                module=module,
                path_base_dir=path_base_dir,
            )
        )
    return sorted(statuses, key=lambda item: (item.module, item.addon_root))


def technical_doc_needs_action(status: TechnicalDocumentationStatus) -> bool:
    """Return whether a status still needs technical-documentation work."""

    return status.status != "up_to_date"


def select_next_technical_doc_status(
    statuses: list[TechnicalDocumentationStatus],
) -> TechnicalDocumentationStatus | None:
    """Select the next addon that should receive technical-doc attention."""

    candidates = [status for status in statuses if technical_doc_needs_action(status)]
    if not candidates:
        return None
    return sorted(
        candidates,
        key=lambda item: (
            TECHNICAL_DOC_STATUS_RANK.get(item.status, 500),
            item.module,
            item.addon_root,
        ),
    )[0]


def parse_markdown_table(text: str) -> list[list[str]] | None:
    """Parse a markdown table into a list of rows, excluding separator row."""

    lines = [
        line.strip() for line in text.replace("\r\n", "\n").split("\n") if line.strip()
    ]
    if len(lines) < 2:
        return None

    def _split(line: str) -> list[str] | None:
        if "|" not in line:
            return None
        raw = line.strip()
        if raw.startswith("|"):
            raw = raw[1:]
        if raw.endswith("|"):
            raw = raw[:-1]
        return [cell.strip() for cell in raw.split("|")]

    header = _split(lines[0])
    separator = _split(lines[1])
    if header is None or separator is None or len(header) != len(separator):
        return None
    if any(not re.fullmatch(r":?-{3,}:?", cell.replace(" ", "")) for cell in separator):
        return None
    rows = [header]
    for line in lines[2:]:
        cells = _split(line)
        if cells is None:
            return None
        rows.append(cells)
    return rows


def normalize_markdown_for_significance(text: str) -> str:
    """Normalize markdown so spacing/alignment-only changes become equal."""

    table_rows = parse_markdown_table(text)
    if table_rows is not None:
        return "\n".join("|".join(cell.strip() for cell in row) for row in table_rows)

    normalized_lines: list[str] = []
    for raw_line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw_line.rstrip()
        stripped = line.strip()
        if stripped.startswith("<!--") and "oduit:" in stripped:
            continue
        if stripped == "":
            if normalized_lines and normalized_lines[-1] == "":
                continue
            normalized_lines.append("")
            continue
        normalized_lines.append(stripped)
    return "\n".join(normalized_lines).strip()


def _render_diff(old_text: str, new_text: str) -> str | None:
    diff_lines = list(
        unified_diff(
            old_text.splitlines(),
            new_text.splitlines(),
            fromfile="report_snapshot",
            tofile="current_evidence",
            lineterm="",
        )
    )
    if not diff_lines:
        return None
    return "\n".join(diff_lines)


def diff_report_against_evidence(
    *,
    addon_root: str | Path,
    module: str,
    path_base_dir: Path | None = None,
    include_diff: bool = False,
    significant_only: bool = False,
) -> TechnicalEvidenceDiffResult:
    """Diff report snapshot blocks against the current evidence document."""

    root = Path(addon_root).resolve(strict=False)
    report_path, _ = technical_doc_paths(root)
    evidence_path, evidence_metadata_path = technical_evidence_paths(root)
    storage_base = (
        path_base_dir.resolve(strict=False)
        if path_base_dir is not None
        else Path.cwd().resolve(strict=False)
    )
    result = TechnicalEvidenceDiffResult(
        module=module,
        addon_root=_portable_path(root, base_dir=storage_base),
        report_path=_portable_path(report_path, base_dir=storage_base),
        evidence_path=_portable_path(evidence_path, base_dir=storage_base),
        evidence_metadata_path=_portable_path(
            evidence_metadata_path, base_dir=storage_base
        ),
        status="up_to_date",
    )
    if not report_path.exists():
        result.status = "missing_report"
        result.remediation.append(
            "Generate the report with docs technical-report first."
        )
        return result
    if not evidence_path.exists() or not evidence_metadata_path.exists():
        result.status = "missing_evidence"
        result.remediation.append(
            "Run oduit docs technical-evidence"
            f" @addons/{module} --output-in-addon first."
        )
        return result

    evidence_metadata, metadata_warnings = load_technical_evidence_metadata(
        evidence_metadata_path
    )
    result.warnings.extend(metadata_warnings)
    if evidence_metadata is None:
        result.status = "invalid"
        return result
    result.current_evidence_version = evidence_metadata.evidence_version

    try:
        evidence_blocks = parse_generated_blocks(
            evidence_path.read_text(encoding="utf-8")
        )
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        result.status = "invalid"
        result.warnings.append(f"Failed to parse evidence markdown: {exc}")
        return result
    evidence_by_id = {block.id: block for block in evidence_blocks}

    try:
        report_snapshots = parse_evidence_snapshot_blocks(
            report_path.read_text(encoding="utf-8")
        )
    except (OSError, UnicodeDecodeError, ValueError) as exc:
        result.status = "invalid"
        result.entries.append(
            TechnicalEvidenceDiffEntry(
                block_id="__marker__",
                status="marker_invalid",
                significant=True,
                message=str(exc),
            )
        )
        result.warnings.append(str(exc))
        return result

    entries: list[TechnicalEvidenceDiffEntry] = []
    for snapshot in report_snapshots:
        snapshot_sha = snapshot.metadata.get("snapshot_sha256")
        snapshot_sha_str = snapshot_sha if isinstance(snapshot_sha, str) else None
        current_snapshot_sha = sha256_text(snapshot.body)
        entry = TechnicalEvidenceDiffEntry(
            block_id=snapshot.block_id,
            renderer=snapshot.renderer,
            old_evidence_version=snapshot.evidence_version,
            current_evidence_version=evidence_metadata.evidence_version,
            old_source_sha256=(
                snapshot.metadata.get("source_sha256")
                if isinstance(snapshot.metadata.get("source_sha256"), str)
                else None
            ),
            old_content_sha256=(
                snapshot.metadata.get("content_sha256")
                if isinstance(snapshot.metadata.get("content_sha256"), str)
                else None
            ),
            snapshot_sha256=snapshot_sha_str,
            current_snapshot_sha256=current_snapshot_sha,
        )
        current_block = evidence_by_id.get(snapshot.block_id)
        if current_snapshot_sha != snapshot_sha_str:
            entry.status = "snapshot_edited"
            entry.significant = True
            entry.message = "Snapshot body differs from recorded snapshot_sha256."
            entries.append(entry)
            continue
        if current_block is None:
            entry.status = "current_block_missing"
            entry.significant = True
            entry.message = "Referenced evidence block does not exist in evidence file."
            entries.append(entry)
            continue
        entry.current_source_sha256 = (
            current_block.metadata.get("source_sha256")
            if isinstance(current_block.metadata.get("source_sha256"), str)
            else None
        )
        entry.current_content_sha256 = (
            current_block.metadata.get("content_sha256")
            if isinstance(current_block.metadata.get("content_sha256"), str)
            else sha256_text(current_block.body)
        )
        stale = (
            entry.old_source_sha256 != entry.current_source_sha256
            or entry.old_content_sha256 != entry.current_content_sha256
        )
        if not stale:
            entry.status = "unchanged"
            entries.append(entry)
            continue

        normalized_snapshot = normalize_markdown_for_significance(snapshot.body)
        normalized_current = normalize_markdown_for_significance(current_block.body)
        entry.significant = normalized_snapshot != normalized_current
        entry.status = (
            "snapshot_stale" if entry.significant else "snapshot_stale_insignificant"
        )
        if include_diff:
            entry.diff = _render_diff(snapshot.body, current_block.body)
        entries.append(entry)

    result.snapshot_count = len(report_snapshots)
    if significant_only:
        entries = [entry for entry in entries if entry.significant]
    result.entries = entries
    result.stale_count = sum(
        1
        for entry in entries
        if entry.status in {"snapshot_stale", "snapshot_stale_insignificant"}
    )
    result.edited_snapshot_count = sum(
        1 for entry in entries if entry.status == "snapshot_edited"
    )
    result.missing_current_block_count = sum(
        1 for entry in entries if entry.status == "current_block_missing"
    )
    if any(entry.status == "snapshot_edited" for entry in entries):
        result.status = "edited_snapshots"
    elif any(
        entry.status in {"snapshot_stale", "current_block_missing"} for entry in entries
    ):
        result.status = "stale"
    else:
        result.status = "up_to_date"
    return result


def _canonical_json_bytes(data: Any) -> bytes:
    return json.dumps(
        data,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def _should_track_file(relative_path: str) -> bool:
    path = Path(relative_path)
    normalized = path.as_posix()
    if normalized in {
        f"docs/{TECHNICAL_DOC_FILENAME}",
        f"docs/{TECHNICAL_DOC_METADATA_FILENAME}",
        f"docs/{TECHNICAL_EVIDENCE_FILENAME}",
        f"docs/{TECHNICAL_EVIDENCE_METADATA_FILENAME}",
    }:
        return False
    if path.name in _EXCLUDED_FILENAMES:
        return False
    if path.suffix.lower() in _EXCLUDED_SUFFIXES:
        return False
    if any(part in _EXCLUDED_DIRS for part in path.parts):
        return False
    if normalized.startswith("docs/_build/"):
        return False
    if normalized.startswith("docs/") and path.suffix.lower() in {".html", ".pdf"}:
        return False
    if path.name in _MANIFEST_FILENAMES:
        return True
    return path.suffix.lower() in _TRACKED_EXTENSIONS


def _metadata_from_dict(data: dict[str, Any]) -> TechnicalDocumentationMetadata | None:
    required_text_fields = ("module", "addon_root", "doc_path", "metadata_path")
    if any(
        not isinstance(data.get(field_name), str) for field_name in required_text_fields
    ):
        return None

    source_snapshot = _source_snapshot_from_dict(data.get("source_snapshot"))
    document_snapshot = _document_snapshot_from_dict(data.get("document_snapshot"))
    if source_snapshot is None or document_snapshot is None:
        return None

    return TechnicalDocumentationMetadata(
        schema_version=str(data.get("schema_version", TECHNICAL_DOC_SCHEMA_VERSION)),
        module=str(data["module"]),
        addon_root=str(data["addon_root"]),
        doc_path=str(data["doc_path"]),
        metadata_path=str(data["metadata_path"]),
        template=str(data.get("template", "arc42-addon-v1")),
        created_at=_optional_str(data.get("created_at")),
        last_generated_at=_optional_str(data.get("last_generated_at")),
        generation_count=int(data.get("generation_count", 0) or 0),
        generator=(
            dict(data.get("generator", {}))
            if isinstance(data.get("generator"), dict)
            else {}
        ),
        generation_options=(
            dict(data.get("generation_options", {}))
            if isinstance(data.get("generation_options"), dict)
            else {}
        ),
        evidence_counts=(
            {
                str(key): int(value)
                for key, value in data.get("evidence_counts", {}).items()
            }
            if isinstance(data.get("evidence_counts"), dict)
            else {}
        ),
        source_snapshot=source_snapshot,
        document_snapshot=document_snapshot,
        generated_blocks=_generated_blocks_from_list(data.get("generated_blocks")),
        refresh_count=int(data.get("refresh_count", 0) or 0),
        last_refreshed_at=_optional_str(data.get("last_refreshed_at")),
        reviewed_at=_optional_str(data.get("reviewed_at")),
        reviewed_by=_optional_str(data.get("reviewed_by")),
        review_note=_optional_str(data.get("review_note")),
        warnings=list(data.get("warnings", []))
        if isinstance(data.get("warnings"), list)
        else [],
    )


def _evidence_metadata_from_dict(
    data: dict[str, Any],
) -> TechnicalEvidenceMetadata | None:
    required_text_fields = ("module", "addon_root", "evidence_path", "metadata_path")
    if any(
        not isinstance(data.get(field_name), str) for field_name in required_text_fields
    ):
        return None
    source_snapshot = _source_snapshot_from_dict(data.get("source_snapshot"))
    evidence_document_snapshot = _document_snapshot_from_dict(
        data.get("evidence_document_snapshot")
    )
    if source_snapshot is None or evidence_document_snapshot is None:
        return None
    return TechnicalEvidenceMetadata(
        schema_version=str(
            data.get("schema_version", TECHNICAL_EVIDENCE_SCHEMA_VERSION)
        ),
        module=str(data["module"]),
        addon_root=str(data["addon_root"]),
        evidence_path=str(data["evidence_path"]),
        metadata_path=str(data["metadata_path"]),
        template=str(data.get("template", "arc42-evidence-v1")),
        evidence_version=int(data.get("evidence_version", 0) or 0),
        created_at=_optional_str(data.get("created_at")),
        last_generated_at=_optional_str(data.get("last_generated_at")),
        generator=(
            dict(data.get("generator", {}))
            if isinstance(data.get("generator"), dict)
            else {}
        ),
        generation_options=(
            dict(data.get("generation_options", {}))
            if isinstance(data.get("generation_options"), dict)
            else {}
        ),
        evidence_counts=(
            {
                str(key): int(value)
                for key, value in data.get("evidence_counts", {}).items()
            }
            if isinstance(data.get("evidence_counts"), dict)
            else {}
        ),
        source_snapshot=source_snapshot,
        evidence_document_snapshot=evidence_document_snapshot,
        generated_blocks=_generated_blocks_from_list(data.get("generated_blocks")),
        warnings=list(data.get("warnings", []))
        if isinstance(data.get("warnings"), list)
        else [],
    )


def _generated_blocks_from_document(
    doc_path: Path,
) -> list[TechnicalDocumentationGeneratedBlock]:
    try:
        markdown = doc_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []
    try:
        blocks = parse_generated_blocks(markdown)
    except ValueError:
        return []
    generated: list[TechnicalDocumentationGeneratedBlock] = []
    for block in blocks:
        generated.append(
            TechnicalDocumentationGeneratedBlock(
                id=block.id,
                renderer=block.renderer,
                schema_version=block.schema_version,
                source_sha256=(
                    block.metadata.get("source_sha256")
                    if isinstance(block.metadata.get("source_sha256"), str)
                    else ""
                ),
                content_sha256=(
                    block.metadata.get("content_sha256")
                    if isinstance(block.metadata.get("content_sha256"), str)
                    else sha256_text(block.body)
                ),
                line_count=len(block.body.splitlines()),
            )
        )
    return generated


def _generated_blocks_from_list(
    data: Any,
) -> list[TechnicalDocumentationGeneratedBlock]:
    if not isinstance(data, list):
        return []
    generated: list[TechnicalDocumentationGeneratedBlock] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        block_id = item.get("id")
        renderer = item.get("renderer")
        if not isinstance(block_id, str) or not isinstance(renderer, str):
            continue
        generated.append(
            TechnicalDocumentationGeneratedBlock(
                id=block_id,
                renderer=renderer,
                schema_version=str(
                    item.get("schema_version", "oduit.generated_markdown_block.v1")
                ),
                source_sha256=_optional_str(item.get("source_sha256")) or "",
                content_sha256=_optional_str(item.get("content_sha256")) or "",
                line_count=_optional_int(item.get("line_count")),
                updated_at=_optional_str(item.get("updated_at")),
            )
        )
    return generated


def _source_snapshot_from_dict(data: Any) -> DocumentationSourceSnapshot | None:
    if not isinstance(data, dict):
        return None
    files_data = data.get("files")
    if not isinstance(files_data, list):
        return None
    files: list[DocumentationTrackedFile] = []
    for item in files_data:
        if not isinstance(item, dict):
            return None
        path = item.get("path")
        category = item.get("category")
        if not isinstance(path, str) or not isinstance(category, str):
            return None
        files.append(
            DocumentationTrackedFile(
                path=path,
                category=category,
                size_bytes=_optional_int(item.get("size_bytes")),
                sha256=_optional_str(item.get("sha256")),
            )
        )
    return DocumentationSourceSnapshot(
        algorithm=str(data.get("algorithm", "sha256")),
        fingerprint=str(data.get("fingerprint", "")),
        file_count=int(data.get("file_count", len(files)) or 0),
        files=files,
    )


def _document_snapshot_from_dict(data: Any) -> DocumentationDocumentSnapshot | None:
    if not isinstance(data, dict):
        return None
    fingerprint = data.get("fingerprint")
    if not isinstance(fingerprint, str):
        return None
    return DocumentationDocumentSnapshot(
        algorithm=str(data.get("algorithm", "sha256")),
        fingerprint=fingerprint,
        size_bytes=_optional_int(data.get("size_bytes")),
        line_count=_optional_int(data.get("line_count")),
    )


def _optional_int(value: Any) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _optional_str(value: Any) -> str | None:
    return value if isinstance(value, str) else None


def _portable_path(path: Path, *, base_dir: Path | None = None) -> str:
    resolved = path.resolve(strict=False)
    for base in [base_dir, Path.cwd()]:
        if base is None:
            continue
        try:
            value = resolved.relative_to(base.resolve(strict=False)).as_posix()
        except ValueError:
            continue
        return value or "."
    return resolved.as_posix()


def _metadata_relative_path(
    path: Path,
    *,
    addon_root: Path,
    base_dir: Path | None = None,
) -> str:
    resolved_path = path.resolve(strict=False)
    resolved_root = addon_root.resolve(strict=False)
    try:
        return resolved_path.relative_to(resolved_root).as_posix()
    except ValueError:
        return _portable_path(resolved_path, base_dir=base_dir)


def _normalize_template_name(template: str) -> str:
    return "arc42-addon-v1" if template == "arc42" else template


def _evidence_counts(bundle: TechnicalDocumentation) -> dict[str, int]:
    inventory = bundle.technical_inventory
    addon_doc = bundle.addon_documentation
    recommended_tests = 0
    models = 0
    if addon_doc is not None:
        if addon_doc.model_inventory is not None:
            models = len(addon_doc.model_inventory.models)
        tests = addon_doc.recommended_tests.get("tests")
        if isinstance(tests, list):
            recommended_tests = len(tests)
    return {
        "models": models,
        "xml_records": len(getattr(inventory, "xml_records", []) or []),
        "routes": len(getattr(inventory, "http_routes", []) or []),
        "security_files": len(getattr(inventory, "security_files", []) or []),
        "migration_files": len(getattr(inventory, "migration_files", []) or []),
        "recommended_tests": recommended_tests,
        "todo_markers": len(getattr(inventory, "todo_markers", []) or []),
        "warnings": len(bundle.warnings),
        "remediation": len(bundle.remediation),
    }


def _document_has_generated_header(doc_path: Path) -> bool:
    try:
        return _GENERATED_HEADER_MARKER in doc_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False


def _diff_source_files(
    old_snapshot: DocumentationSourceSnapshot,
    new_snapshot: DocumentationSourceSnapshot,
) -> tuple[list[str], list[str], list[str]]:
    old_by_path = {file_entry.path: file_entry for file_entry in old_snapshot.files}
    new_by_path = {file_entry.path: file_entry for file_entry in new_snapshot.files}
    added_files = sorted(set(new_by_path) - set(old_by_path))
    removed_files = sorted(set(old_by_path) - set(new_by_path))
    changed_files = sorted(
        path
        for path in set(old_by_path) & set(new_by_path)
        if old_by_path[path].sha256 != new_by_path[path].sha256
    )
    return changed_files, added_files, removed_files


def _is_addon_root(path: Path) -> bool:
    return any((path / filename).exists() for filename in _MANIFEST_FILENAMES)


def _module_from_root(path: Path) -> str:
    return path.name


def _scan_addons_under(directory: Path) -> list[tuple[str, str]]:
    resolved_directory = directory.resolve(strict=False)
    if _is_addon_root(resolved_directory):
        return [(_module_from_root(resolved_directory), resolved_directory.as_posix())]
    if not resolved_directory.is_dir():
        return []
    result: list[tuple[str, str]] = []
    for child in sorted(resolved_directory.iterdir()):
        if child.is_dir() and _is_addon_root(child):
            result.append(
                (_module_from_root(child), child.resolve(strict=False).as_posix())
            )
    return result


def _resolve_select_path(select_dir: str, *, path_base_dir: Path | None) -> Path:
    selected = Path(select_dir).expanduser()
    if selected.is_absolute():
        return selected.resolve(strict=False)
    base = path_base_dir or Path.cwd()
    return (base / selected).resolve(strict=False)


def _resolve_metadata_path(value: str, *, base_dir: Path | None) -> Path:
    path = Path(value).expanduser()
    if path.is_absolute():
        return path.resolve(strict=False)
    if base_dir is None:
        return path.resolve(strict=False)
    return (base_dir / path).resolve(strict=False)


def _iter_addon_roots(
    addons_path: str,
    *,
    select_dir: str | None,
    path_base_dir: Path | None = None,
) -> list[tuple[str, str]]:
    addon_roots: list[tuple[str, str]] = []
    seen_roots: set[str] = set()
    configured_paths = [
        Path(configured_path).resolve(strict=False)
        for configured_path in AddonsPathManager(addons_path).get_configured_paths()
    ]

    candidate_directories: list[Path]
    if select_dir is not None:
        selected_path = _resolve_select_path(select_dir, path_base_dir=path_base_dir)
        if selected_path.exists():
            candidate_directories = [selected_path]
        else:
            candidate_directories = [
                base_path
                for base_path in configured_paths
                if base_path.name == select_dir
            ]
    else:
        candidate_directories = configured_paths

    for directory in candidate_directories:
        for module, addon_root in _scan_addons_under(directory):
            if addon_root in seen_roots:
                continue
            seen_roots.add(addon_root)
            addon_roots.append((module, addon_root))
    return addon_roots
