python_bin = "/home/nahrstaedt/src/odoo17/.venv/bin/python3"
coverage_bin = "/home/nahrstaedt/src/odoo17/.venv/bin/coverage"
odoo_bin = "/home/nahrstaedt/src/odoo17/odoo/odoo-bin"
db_name = "test_db_17_tmp4"
db_user = "nahrstaedt"
db_password = "odoo-v17"
data_dir = "/home/nahrstaedt/.local/share/OdooTestTmp4"
http_port = 8075
gevent_port = 8076
db_port = 5432
addons_path = [
  "/home/nahrstaedt/src/odoo17/odoo/addons",
  "/home/nahrstaedt/src/odoo17/oduit/integration_tests/myaddons/",
]
