name: CodeCov
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
    - name: 'generate report'
      run: |
        pip install coverage click
        pip install -e .
        coverage run -m unittest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # required
